export const ADD_TASK_PENDING = 'ADD_TASK_PENDING'
export const ADD_TASK_FULFILLED = 'ADD_TASK_FULFILLED'
export const ADD_TASK_REJECTED = 'ADD_TASK_REJECTED'

export const FETCH_TASKS_PENDING = 'FETCH_TASKS_PENDING'
export const FETCH_TASKS_FULFILLED = 'FETCH_TASKS_FULFILLED'
export const FETCH_TASKS_REJECTED = 'FETCH_TASKS_REJECTED'

export const EDIT_TASK_PENDING = 'EDIT_TASK_PENDING'
export const EDIT_TASK_FULFILLED = 'EDIT_TASK_FULFILLED'
export const EDIT_TASK_REJECTED = 'EDIT_TASK_REJECTED'

export const DELETE_TASK_PENDING = 'DELETE_TASK_PENDING'
export const DELETE_TASK_FULFILLED = 'DELETE_TASK_FULFILLED'
export const DELETE_TASK_REJECTED = 'DELETE_TASK_REJECTED'

export const apiUrl = "http://localhost:5000/api";
